# 📊 NumPy Data Analysis

A practical analysis of student performance using NumPy.

### Topics
- Arrays
- Statistics
- Aggregation
- Indexing
- Filtering
- Data Analysis

In [2]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [72, 88, 81],
    [95, 91, 89],
    [64, 70, 68],
    [88, 84, 90],
    [76, 79, 75]
])

subjects = ["Python", "Math", "Statistics"]

print("Student Marks:")
print(marks)

Student Marks:
[[85 78 92]
 [72 88 81]
 [95 91 89]
 [64 70 68]
 [88 84 90]
 [76 79 75]]


In [3]:
print("Overall Average:", np.mean(marks))
print("Highest Mark:", np.max(marks))
print("Lowest Mark:", np.min(marks))
print("Median:", np.median(marks))

Overall Average: 81.38888888888889
Highest Mark: 95
Lowest Mark: 64
Median: 82.5


In [4]:
student_average = np.mean(marks, axis=1)

print("Student Averages:")

for i, avg in enumerate(student_average, 1):
    print(f"Student {i}: {avg:.2f}")

Student Averages:
Student 1: 85.00
Student 2: 80.33
Student 3: 91.67
Student 4: 67.33
Student 5: 87.33
Student 6: 76.67


In [5]:
subject_average = np.mean(marks, axis=0)

print("Subject Averages:")

for subject, avg in zip(subjects, subject_average):
    print(f"{subject}: {avg:.2f}")

Subject Averages:
Python: 80.00
Math: 81.67
Statistics: 82.50


In [7]:
top_student = np.argmax(student_average)

print("Top Student:", top_student + 1)
print("Average:", round(student_average[top_student], 2))

high_performers = marks[student_average > 85]

print("\nHigh Performing Students:")
print(high_performers)

Top Student: 3
Average: 91.67

High Performing Students:
[[95 91 89]
 [88 84 90]]


In [ ]:
## 🔍 Key Insights

- Calculated overall student performance.
- Compared student-wise and subject-wise averages.
- Identified the top-performing student.
- Used NumPy filtering to identify high performers.
- Applied NumPy statistical functions for data analysis.

### 🛠️ Tools
Python • NumPy • Jupyter Notebook